title = "Test Config for MarketSim"
message = "File Loaded"
num_buyers = 4
num_sellers = 4

[B1]
name = "B1"
type = "B"
num_units = 3
min_value = 200
max_value = 400
trader_type = "Kaplan"

[B2]
name = "B2"
type = "B"
num_units = 3
min_value = 200
max_value = 400
trader_type = "Kaplan"

[B3]
name = "B3"
type = "B"
num_units = 3
min_value = 200
max_value = 400
trader_type = "Kaplan"

[B4]
name = "B4"
type = "B"
num_units = 3
min_value = 200
max_value = 400
trader_type = "Kaplan"

[S1]
name = "S1"
type = "S"
num_units = 3
min_value = 100
max_value = 300
trader_type = "Kaplan"

[S2]
name = "S2"
type = "S"
num_units = 3
min_value = 100
max_value = 300
trader_type = "Kaplan"

[S3]
name = "S3"
type = "S"
num_units = 3
min_value = 100
max_value = 300
trader_type = "Kaplan"

[S4]
name = "S4"
type = "S"
num_units = 3
min_value = 100
max_value = 300
trader_type = "Kaplan"