title = "Test Config for MarketSim"
message = "File Loaded"
num_buyers = 5
num_sellers = 5

[B1]
name = "B1"
type = "B"
num_units = 3
min_value = 200
max_value = 400
trader_type = "Zero Intelligence"

[B2]
name = "B2"
type = "B"
num_units = 3
min_value = 200
max_value = 400
trader_type = "Kaplan"

[B3]
name = "B3"
type = "B"
num_units = 3
min_value = 200
max_value = 400
trader_type = "Persistent Shout"

[B4]
name = "B4"
type = "B"
num_units = 3
min_value = 200
max_value = 400
trader_type = "Skeleton"

[B5]
name = "B5"
type = "B"
num_units = 3
min_value = 200
max_value = 400
trader_type = "Ringuette"

[S1]
name = "S1"
type = "S"
num_units = 3
min_value = 100
max_value = 300
trader_type = "Zero Intelligence"

[S2]
name = "S2"
type = "S"
num_units = 3
min_value = 100
max_value = 300
trader_type = "Kaplan"

[S3]
name = "S3"
type = "S"
num_units = 3
min_value = 100
max_value = 300
trader_type = "Persistent Shout"

[S4]
name = "S4"
type = "S"
num_units = 3
min_value = 100
max_value = 300
trader_type = "Skeleton"

[S5]
name = "S5"
type = "S"
num_units = 3
min_value = 100
max_value = 300
trader_type = "Ringuette"